ECS/plainECS/includes/ecs.h, ECS/plainECS/includes/ecsBaseSystem.h, ECS/plainECS/includes/ecsComponentIterator.h, ECS/plainECS/includes/ecsComponentManager.h, ECS/plainECS/includes/ecsComponentPool.h, ECS/plainECS/includes/ecsEntityManager.h, ECS/plainECS/includes/ecsEventListener.h, ECS/plainECS/includes/ecsSystem.h, ECS/plainECS/includes/ecsTypeFilter.h, ECS/plainECS/includes/ecsUser.h, ECS/plainECS/main.cpp, ECS/plainECS/plainECS.vcxproj, ECS/plainECS/plainECS.vcxproj.filters, ECS/plainECS/src/ecs.cpp, ECS/plainECS/src/ecsComponentManager.cpp, ECS/plainECS/src/ecsEntityManager.cpp, ECS/plainECS/src/ecsEventListener.cpp, ECS/plainECS/src/ecsTypeFilter.cpp, ECS/plainECS/src/ecsUser.cpp
Fixed bugs in event subscriptions. Added Actor to SystemTypeUpdate. Added more getters to ECS for easier debug. ECSUsers (custom systems) have more getters from ECS now.
Exported to libs.
=> Us5_prepECS

Utility/Utility/Utility.vcxproj, Utility/Utility/Utility.vcxproj.filters, Utility/Utility/includes/DebugInfo.h, Utility/Utility_test/DebugInfoTestHeader.h, Utility/Utility_test/Utility_test.vcxproj, Utility/Utility_test/test.cpp
A header-only implementation of a collection of variables gathered under a namespace for easy access everywhere
=> Added DebugInfo header file with included tests

InputHandler/InputHandler/InputHandler.vcxproj, InputHandler/InputHandler/InputHandler.vcxproj.filters, InputHandler/InputHandler/StyleSheet.css, InputHandler/InputHandler/ccTest.html, InputHandler/InputHandler/gridStyle.css, InputHandler/InputHandler/scripts/buttons.js, InputHandler/InputHandler/scripts/script.js
Had free time so made some changes to the HTML to handle a larger grid with a hexagon pattern
=> Created a big grid on the website to handle the size of the decided grid

Physics/Physics/CollisionSystem.cpp, Physics/Physics/MovementSystem.cpp, Physics/Physics/includes/PhysicsEvents.h, Physics/Physics_test/GroundCollision.h, Physics/Physics_test/MovementLogic.h, Physics/Physics_test/ObjectCollision.h, Physics/Physics_test/Physics_test.vcxproj, Physics/Physics_test/TestHelpers.cpp, Physics/Physics_test/TestHelpers.h, Physics/Physics_test/test.cpp
On collision, the entity that moved now reverts the movement and resets the velocity in the most significant direction so the object does not stop entirely on collision but rather slides along the side of the other pretty much.
The solution is not pretty, but it works.
=> Us13 handle object collision

AI/AI/AI.vcxproj, AI/AI/includes/AISystems.h, AI/AI_test/AI_test.vcxproj, AI/AI_test/test.cpp, InputHandler/InputInterpreter/InputInterpreter_Release.props
Will have to be updated in a future sprint.
=> Fixed so that the SwitchStateSystem works for this sprint demo.

Game/GameMain/GameMain.vcxproj.filters, Game/GameMain/gameAudio/AudioECSEvents.h, Game/GameMain/gameAudio/AudioECSSystems.cpp, Game/GameMain/gameAudio/AudioECSSystems.h, Game/GameMain/gameAudio/InitAudio.h
=> Hotfix audio join thread no cable crash

InputHandler/InputHandler/PingingWebsite.cpp, InputHandler/InputHandler/mobileSite.html
made the website scale to the screen to look better on mobiles
Link to test on phone can be found on:
http://htmlpreview.github.io/?https://github.com/Wessebanan/PA2526-Grupp-C/blob/mobileBackground/InputHandler/InputHandler/mobileSite.html
=> Mobile background

ModelLoader/ModelLoader/Fbx_Loader.cpp
Changed the conversion matrix for normals in the model loader to correct them.
All tests still pass.
=> 🔥HOTFIX🔥 Normals

Game/GameMain/gameAI/AIEcsFunctions.cpp
Add padding to UI text for TV format.
=> 🔥HOTFIX🔥_Add_Padding

Game/GameMain/Input/InterpretWebSystems.cpp, Game/GameMain/gameAI/AISystems.h, Game/GameMain/gameGameLoop/GameLoopSystems.cpp
Fixed so that the player can send a flee command to their army from their phone.
=> Switch_State_Fix

Game/GameMain/InitHttpServer.h, Game/GameMain/Input/InitInputSystems.cpp, Game/GameMain/main.cpp, Game/Sites/mobileSite.html, InputHandler/InputHandler/InputBackend.cpp, InputHandler/InputHandler/includes/InputBackend.h, InputHandler/InputHandler/includes/webConnection.h, InputHandler/InputHandler/mobileSite.html, InputHandler/InputHandler/webConnection.cpp
Made functions from 
html -> webconnetion ->inputbackend -> inputSystems -> pingevent
=> Implemented ping from website

Game/GameMain/Physics/FightingSystem.cpp, Game/GameMain/Physics/FightingSystem.h
Sound on damage and death, sometimes death sounds refuse to play but this lies in the sound engine.
=> US19_Fight_Sound_Effects

AI/AI/includes/GridProp.h, Game/GameMain/main.cpp
Added includes in gridProp that was broke (?). Works now though.
=> Cleared comments in main.

ModelLoader/ModelLoader/includes/Fbx_Loader.h
Added random desync modifier so not everyone swings at the same time :)
=> 🔥Hotfix🔥 Animation Desync

Game/GameMain/gameAI/AISystems.h, Game/GameMain/gameAI/GridEcsFunctions.cpp
Fixed so that units with weapons follow their closest ally instead of competing with them over the loot.
=> US17_Loot_Block

Game/GameMain/gameGameLoop/GameLoopSystems.cpp, Game/GameMain/gameGameLoop/GameLoopSystems.h, Game/GameMain/gameUtility/CameraEcsFunctions.cpp, Game/GameMain/gameUtility/CameraEcsFunctions.h, Game/GameMain/gameUtility/CameraSystems.h, Game/GameMain/gameUtility/InitCamera.h
The game will start with an overlook camera
When the round start it will create the update for the camera
When the round is over it will snap back to overlook
There are plans for a smoother transition but that will be in laster sprints
=> US5 Prephase camera

Game/GameMain/GameMain.vcxproj, Game/GameMain/GameMain.vcxproj.filters, Game/GameMain/Input/InterpretWebSystems.cpp, Game/GameMain/gameTraps/InitTraps.h, Game/GameMain/gameTraps/TrapEvents.h, Game/GameMain/gameTraps/TrapSystems.cpp, Game/GameMain/gameTraps/TrapSystems.h, Game/GameMain/main.cpp
Fire Trap event and event reader
A debugging tool is commented in the flee command
=> Us11 fire trap

Game/GameMain/gameGameLoop/GameLoopSystems.cpp, Game/Sites/mobileSite.html
The bugs we found with the prephase interface
New traps each round
The traps now correspond with the GAMEs traps
=> new traps each time they get pprep

Game/GameMain/Input/InterpretWebSystems.cpp, Game/GameMain/gameTraps/InitTraps.h, Game/GameMain/gameTraps/TrapSystems.cpp, Game/GameMain/gameTraps/TrapSystems.h
MERGED FREEZING IN HERE ASWELL SO THAT NEEDS TO BE FIRST
Sends the unit flying to a random tile, so it will be more likely to fly in a direction where there are tiles.
The naming of my components is called LHURE so it wont conflict with Mackes trapcomponents
To test, un-comment the code in Interpertre for "flee", then all units will be hit with the trap at once
=> Us11 spring trap

Game/GameMain/GameMain.vcxproj, Game/GameMain/GameMain.vcxproj.filters, Game/GameMain/InitHttpServer.h, Game/Sites/newSite.html
Ändrade fäger, och satte en outline på några delar,
Fixade med en del alignment,
Den gamla sidan finns fortfarande kvar men den nya är den som skickas ut
starta spelat och ta upp det på telefonen och kör och se om du kan se alla knappar osv på den
=> switched to a new site and cleaned up the HTML

Game/Sites/newSite.html
Added a name field so players can send thier name to the game,
This is only visable while waitign for all joined players to press ready, so you cant send a name if joining late
Also changed the text after request
=> Us18 web side

ECS/plainECS/includes/ecsBaseComponent.h, ECS/plainECS/src/ecsComponentPool.cpp, ECS/plainECS_test/ecsObjectsForTesting.h
- Fixed so that a components destructor is called when it's removed.
=> US23 Component Destructor

Game/GameMain/gameAI/AISystems.cpp, Game/GameMain/gameAI/AISystems.h
Added some sanity checks to the AI systems.
=> US27_Sanity_Checks_Ganon

Game/GameMain/Physics/CollisionSystem.cpp, Game/GameMain/Physics/FightingSystem.cpp, Game/GameMain/Physics/InitPhysics.h, Game/GameMain/Physics/PhysicsComponents.h, Game/GameMain/gameGameLoop/GameLoopSystems.cpp, Game/GameMain/gameGameLoop/GameLoopSystems.h, Game/GameMain/gameWeapons/InitWeapons.cpp, Game/GameMain/gameWeapons/WeaponSpawner.cpp, Game/GameMain/main.cpp
made some sanity checks and also removed mesh component entirely .
=> Us27 sanitary chokes robin

Game/GameMain/gameGameLoop/GameLoopSystems.cpp, Game/GameMain/gameTraps/TrapSystems.cpp
gick över gameloop systems och trap systems och la in lite mer sanity chekcs
=> Us27 sanity lhure

Game/GameMain/gameWeapons/WeaponSpawner.cpp, Game/GameMain/gameWeapons/WeaponSpawner.h
Added inner radius as critera to spawn weapons.
=> Added inner radius as criteria for weapon spawning.

Game/GameMain/Input/InterpretWebSystems.cpp, Game/GameMain/gameGraphics/InitParticles.h, Game/GameMain/gameGraphics/ParticleECSComponents.h, Game/GameMain/gameGraphics/ParticleECSSystems.cpp, Game/GameMain/gameGraphics/ParticleECSSystems.h, Game/GameMain/gameTraps/TrapSystems.cpp
När en unit går på en trap får de particlar på sig som sak göra det tydligare att de har blivit träffade
Kan testa lätt genom att kommentera in koden i flee commandot, det kommer lägga eld på 3 untits. kommer krasha om du spammar men det är bara pga hur jag testar
=> Us4 fire trap

Game/GameMain/gameTraps/InitTraps.cpp, Game/GameMain/gameTraps/TrapCollisionSystem.cpp, Game/GameMain/gameTraps/TrapComponents.h, Game/GameMain/gameTraps/TrapEvents.h, Game/GameMain/gameTraps/TrapSpawnerSystems.cpp, Game/GameMain/gameTraps/TrapSystems.cpp, Game/GameMain/gameTraps/TrapSystems.h, Game/GameMain/main.cpp
Send the tile up and retracts over time
You can test easily but uncomment the code in the end of initAll()
=> US4_Spring trap effect

Game/GameMain/Input/InterpretWebSystems.cpp, Game/GameMain/gameAudio/AudioECSComponents.h, Game/GameMain/gameAudio/AudioECSSystems.cpp, Game/GameMain/gameAudio/AudioECSSystems.h, Game/GameMain/gameAudio/InitAudio.h
Based on the distance to attacking units targets, the drum track varies in intensity
=> Us25 drums when battle

Game/GameMain/Input/InterpretWebSystems.cpp, Game/GameMain/gameGameLoop/GameLoopSystems.cpp
Now has a better loop, also the problem was i used the wrong cordinates before
To test you can change WEBGAMESTATE::WAITING to PREPHASE
with this you can place traps, to refresh the traps just reload and rejoin
=> Us4 trap spawning correct

Game/GameMain/gameWeapons/WeaponSpawner.cpp
Hammer now lands higher above ground so its more obvious
=> 🔥 HOTFIX 🔥 Hammer Fix Visibility

Game/GameMain/Renderers/Renderers.cpp, Game/Sites/newSite.html, InputHandler/InputHandler/includes/webConnection.h, InputHandler/InputHandler/webConnection.cpp
Now has 4 balls at the top of the site.
They will light up when someone joins the game.
Also made it so that user who join when the game is full gets told that
=> Us5 mobile ui

Game/GameMain/gameAI/AISystems.cpp
Will go into loot state but not vibrate
Try it out and see if I need to fix it
=> Us8 no response on loot

Game/GameMain/gameGraphics/InitGraphics.h, Game/GameMain/gameUtility/CameraEcsFunctions.cpp, Game/GameMain/gameUtility/CameraSystems.cpp, Game/GameMain/gameUtility/GlobalsCamera.h
Changed the FOV to 70 instead of 90. Zoomed out the overlook camera so that the overlay fits the map again.
=> US30_Test_New_FOV

Game/GameMain/gameGameLoop/GameLoopSystems.cpp
Now replaces the names with CPU when they have AIBrain
And set the name when they remove the brain
=> CPU om det är en AI som spelar

AI/AI/includes/AIGlobals.h, Game/GameMain/Input/InterpretWebSystems.cpp, Game/Sites/newSite.html
hopefully fixed the bug and renamed on website
=> renamed ping to taunt

ModelLoader/ModelLoader/includes/Fbx_Loader.h
Reduced the crossfade duration between animations, makes it look more responsive and less sluggish.
=> 🔥HOTFIX🔥 Smoother animation transitions

Game/GameMain/Input/InitInputSystems.cpp, InputHandler/InputHandler/webConnection.cpp
Fixade buggar som är 1000% mackes fel
=> Mackes buggfixbranch

Game/Sites/newSite.html, InputHandler/InputHandler/includes/webConnection.h, InputHandler/InputHandler/webConnection.cpp
Att ha globala variabler så som jag gjorde innan gav ibland korrupta medelanden
Nu har jag lagt till en till variable för att se om man vill skicka trapsen, samt att man skickar och sparar informationen på PCn istället
=> No global trap

Game/GameMain/gameGraphics/DepthPrePassRenderingPipeline.cpp, Game/GameMain/gameGraphics/ForwardRenderingPipeline.cpp, Game/GameMain/gameGraphics/Shaders/PS_Default.hlsl
Depth-Pre pass buffer is now re-used rather than copied and is read-only on second pass. Allows for SRV of the resource as well.
=> Made SSAO Faster
